### PR TITLE
.rst formatting fixes in the long description

### PR DESCRIPTION
**Pull request by reinout**
Mostly replacing `:` with `::` so that the code examples are formatted properly.

Also limited the line lengths a bit. And mentioned the AST :-)

### CODE REVIEW

**Comment by reinout** [comment]
@gforcada, do you have a pypi account?

**Comment by gforcada** [comment]
@reinout, yes: https://pypi.org/user/gilforcada/

**Comment by reinout** [comment]
I released it; the formatting looks OK now.

I've added you as maintainer on pypi. Releasing is the regular "fullrelease".

**Comment by gforcada** [comment]
@reinout cool! thanks for the pypi rights :bowing_man: should we report this to readme_renderer and/or wharehouse? :thinking:

**Comment by reinout** [comment]
There are no problems with readme_renderer: that one only looks at the long_description (which was fine).

My guess: warehouse. If I'm logged in and I go to https://pypi.org/manage/project/z3c.dependencychecker/releases/, I see that halfway 2017, the description-with-newlines was still being rendered OK. From january 2018 on, the description is suddenly empty. Until I fixed it yesterday.

See screenshot.
screenshot from 2018-07-05 13-29-05

**Pull request merged**
