### PR TITLE
Detect packages with dotted names, too

### PR DESCRIPTION
**Pull request by reinout**
I've made a bunch of base-directory-detection changes.

I can now also use it out-of-the-box for zest.releaser and mr.developer.

Also added more logging to help debug various issues that cropped up.

@jone or @gforcada, could one of you take a quick look to see if you spot something that's wrong?

### CODE REVIEW

**Comment by gforcada** [comment]
Nothing screams on my eyes, travis agrees as well, so if you are confident with the test coverage, push the merge button :)

**Comment by reinout** [comment]
@gforcada: are you working on something *right now*? I'd like to move the code from `src/z3c/dependencychecker/` to just `z3c/dependencychecker. So cutting out the `src/`. I'm used to src being the domain of mr.developer :-)

**Comment by reinout** [comment]
See #34

**Comment by reinout** [comment]
Anyway, I already merged that #34 :-)

**Pull request merged**
